#!/usr/bin/env python3
"""End-to-end acceptance regression for the COBOL banking system.

This script drives ./bin/bankmain through a pseudo-terminal so COBOL ACCEPT
behaves like an interactive session.
"""

import os
import pty
import re
import select
import subprocess
import sys
import time
from datetime import datetime, timedelta
from typing import List, Tuple


ROOT = os.path.dirname(os.path.abspath(__file__))
BANKMAIN = os.path.join(ROOT, "bin", "bankmain")
LIBPATH = os.path.join(ROOT, "bin")


def run_session(inputs: List[str], timeout: float = 35.0, delay: float = 0.07) -> str:
    if not os.path.exists(BANKMAIN):
        raise FileNotFoundError("Executable not found: ./bin/bankmain")

    env = dict(os.environ)
    env["COB_LIBRARY_PATH"] = LIBPATH

    master_fd, slave_fd = pty.openpty()
    proc = subprocess.Popen(
        [BANKMAIN],
        cwd=ROOT,
        stdin=slave_fd,
        stdout=slave_fd,
        stderr=slave_fd,
        env=env,
        close_fds=True,
    )
    os.close(slave_fd)

    output_chunks: List[str] = []
    start = time.time()
    index = 0

    try:
        while time.time() - start < timeout:
            if index < len(inputs):
                time.sleep(delay)
                os.write(master_fd, (str(inputs[index]) + "\n").encode())
                index += 1

            ready, _, _ = select.select([master_fd], [], [], 0.05)
            if master_fd in ready:
                try:
                    data = os.read(master_fd, 8192)
                except OSError:
                    break
                if not data:
                    break
                output_chunks.append(data.decode(errors="ignore"))

            if proc.poll() is not None and index >= len(inputs):
                break
    finally:
        if proc.poll() is None:
            proc.terminate()
            time.sleep(0.2)
            if proc.poll() is None:
                proc.kill()
        try:
            os.close(master_fd)
        except OSError:
            pass

    return "".join(output_chunks)


def discover_active_accounts() -> List[Tuple[str, str, str, str]]:
    # Probe today and the two previous days for accounts generated by the
    # account-opening routine (date-based account numbers).
    candidates: List[str] = []
    now = datetime.now().date()
    for days_back in range(0, 3):
        day = now - timedelta(days=days_back)
        base = int(day.strftime("%Y%m%d")) * 100
        for i in range(0, 30):
            candidates.append(str(base + i))

    seq: List[str] = ["1"]
    for number in candidates:
        seq.extend(["02", number])
    seq.extend(["00", "0"])

    out = run_session(seq, timeout=55.0, delay=0.03)

    # Capture complete consultation blocks and retain active accounts.
    pattern = re.compile(
        r"Numero:\s*(\d{10}).*?CPF:\s*([0-9]{11}).*?Email:\s*(.*?)\r?\n"
        r".*?Telefone:\s*([0-9]{8,15}).*?Status:\s*([A-Z])",
        re.S,
    )

    found: List[Tuple[str, str, str, str]] = []
    seen = set()
    for match in pattern.finditer(out):
        num, cpf, email, phone, status = match.groups()
        if status != "A":
            continue
        rec = (num, cpf, email.strip(), phone.strip())
        if rec[0] in seen:
            continue
        seen.add(rec[0])
        found.append(rec)

    return found


def bootstrap_accounts() -> None:
    # Account numbering in BANKACCT is date-based and sequence-based per
    # process instance. Creating multiple accounts in one run can advance the
    # sequence even if earlier writes hit duplicate keys.
    run_session(
        [
            "1",
            "01",
            "AUTO QA 1",
            "12345678909",
            "CC",
            "1234",
            "qa1@example.com",
            "11990000001",
            "01",
            "AUTO QA 2",
            "11144477735",
            "CC",
            "1234",
            "qa2@example.com",
            "11990000002",
            "01",
            "AUTO QA 3",
            "52998224725",
            "CC",
            "1234",
            "qa3@example.com",
            "11990000003",
            "00",
            "0",
        ],
        timeout=80.0,
        delay=0.09,
    )


def make_valid_barcode() -> str:
    payload = "1234567890123456789012345678901234567890123"  # 43 digits
    total = 0
    weight = 2
    for ch in reversed(payload):
        total += int(ch) * weight
        weight += 1
        if weight > 9:
            weight = 2
    dv = 11 - (total % 11)
    if dv > 9:
        dv = 1
    return payload + str(dv)


def check_contains(name: str, output: str, expected_tokens: List[str]) -> Tuple[str, bool, List[str]]:
    missing = [token for token in expected_tokens if token not in output]
    return name, len(missing) == 0, missing


def main() -> int:
    if os.name == "nt":
        print("This script uses pseudo-terminal APIs and should run in WSL/Linux.")
        print("Use: wsl bash -lc 'cd /mnt/c/.../bank && make acceptance'")
        return 2

    accounts = discover_active_accounts()
    if len(accounts) < 2:
        print("[INFO] Fewer than 2 active accounts found. Bootstrapping test accounts...")
        bootstrap_accounts()
        accounts = discover_active_accounts()
    print(f"[INFO] Active accounts discovered: {len(accounts)}")
    for acc in accounts[:4]:
        print(f"[INFO] Account {acc[0]} cpf={acc[1]} email={acc[2]} phone={acc[3]}")

    results: List[Tuple[str, bool, List[str]]] = []

    if len(accounts) < 2:
        results.append((
            "Precondition: at least 2 active accounts",
            False,
            ["Could not discover 2 active accounts in scan range"],
        ))
    else:
        origem = accounts[0][0]
        destino = accounts[1][0]
        destino_email = accounts[1][2]
        destino_cpf = accounts[1][1]

        out_dep = run_session(["2", "01", origem, "700,00", "00", "0"])
        results.append(check_contains("Deposito", out_dep, ["DEPOSITO REALIZADO"]))

        out_ted = run_session(["4", "01", origem, destino, "10,00", "00", "0"])
        results.append(check_contains("TED", out_ted, ["TED EFETUADA"]))

        out_doc = run_session(["4", "02", origem, destino, "10,00", "00", "0"])
        results.append(check_contains("DOC", out_doc, ["DOC EFETUADA"]))

        if "@" in destino_email:
            pix_tipo = "E"
            pix_chave = destino_email
        else:
            pix_tipo = "C"
            pix_chave = destino_cpf

        out_pix = run_session(["4", "03", origem, pix_tipo, pix_chave, "5,00", "00", "0"])
        results.append(check_contains("PIX", out_pix, ["PIX EFETUADO"]))

        barcode = make_valid_barcode()
        out_pay = run_session(["5", "01", origem, barcode, "3,00", "00", "0"])
        results.append(check_contains("Pagamento Boleto", out_pay, ["BOLETO PAGO"]))

    seed = str(int(time.time()))
    client_id = seed[-10:].rjust(10, "7")
    cpf = ("8" + seed)[-11:]

    out_crm = run_session(
        [
            "7",
            "01",
            client_id,
            "CLIENTE QA",
            cpf,
            "RGQA",
            "19920101",
            "F",
            "SO",
            "ANALISTA",
            "4200,00",
            "M",
            "qa@example.com",
            "11977776666",
            "CAMPINAS",
            "SP",
            "13000000",
            "02",
            client_id,
            "03",
            client_id,
            "qa2@example.com",
            "11970000000",
            "COORD",
            "5300,00",
            "A",
            "04",
            client_id,
            "02",
            client_id,
            "00",
            "0",
        ],
        timeout=65.0,
        delay=0.05,
    )
    results.append(
        check_contains(
            "CRM CRUD",
            out_crm,
            ["CLIENTE CADASTRADO", "CADASTRO ATUALIZADO", "CLIENTE INATIVADO", "Status: I"],
        )
    )

    passed = 0
    print("\n=== Acceptance Summary ===")
    for name, ok, missing in results:
        status = "PASS" if ok else "FAIL"
        print(f"[{status}] {name}")
        if ok:
            passed += 1
        else:
            for token in missing:
                print(f"  - missing: {token}")

    print(f"\nResult: {passed}/{len(results)} checks passed")
    return 0 if passed == len(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
